#configuration for PostgreSQL (via docker-compose)
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_vendas
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=usuario
spring.datasource.password=senha123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=false
